### ISSUE TITLE
bootstrap function

### ISSUE THREAD

**Issue by justinobney** [wallabyjs/wallaby-webpack-sample#1]
I cloned the repo, and ran wallaby in Atom, but I am getting the following error in the bootstrap section of the config:

> TypeError: 'undefined' is not an object (evaluating 'window.__moduleBundler.loadTests')

**Comment by ArtemGovorov** [comment]
Did you run `npm install`? I am assuming you did, otherwise the error would be a bit different if I'm not mistaken.

Anyway, it looks like `wallaby-webpack` didn't do the job it's supposed to do, could you please delete `node_modules` folder and try running `npm install` again?

If it doesn't help, could you please try adding [`debug: true` to the config, opening Dev Tools in Atom, restarting wallaby and pasting the Console output](http://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting) here?

**Comment by justinobney** [comment]
That fixed my problem. Thanks!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
